### ISSUE TITLE
[Execution] The code seem to be not runnable on local environment

### ISSUE THREAD

**Issue by wkqls0829** [rong-dai/DisPFL#1]
Hi, I found your work very interesting and confronted some problems while trying to run some experiments of your work.

I have tried to run the experiments by fedml_experiments/standalone/cifar10.sh code as you have mentioned on README.

but, the code confronted many errors because the directory was designated to your local environment and the code required some log file named DISPFL-cifar10-dir0.3-mdlresnet18-csrandom-ERK_init-diff_init-DST-cm500-total_clnt100-neighbor10-dr0.5-activate1.0-seed2022.log.

Could you be kind to upload the independent runnable version of the code including dependency requirements, so that we can test and try out the works of your paper?

Thank you.

**Comment by rong-dai** [comment]
Hi, sorry to reply this late. Does it work well now? I think if you create a directory named 'LOG' that may solve the problem, the log file will be automatically created.

**Comment by wkqls0829** [comment]
yes, I have created cifar10 file under LOG and it works perfectly well thank you :)
